apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: ecommerce
data:
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  KC_DB_USERNAME: keycloak
  KEYCLOAK_ADMIN: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: ecommerce
type: Opaque
data:
  KC_DB_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password"
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= # base64 encoded "admin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.2.5
        args:
        - start-dev
        - --hostname=localhost
        - --hostname-strict=false
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secret
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: ecommerce
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
