apiVersion: v1
kind: ConfigMap
metadata:
  name: refund-service-config
  namespace: ecommerce
data:
  SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/refund-service?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  KAFKA_BOOTSTRAP_SERVERS: broker:29092
---
apiVersion: v1
kind: Secret
metadata:
  name: refund-service-secret
  namespace: ecommerce
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cm9vdA== # base64 encoded "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: refund-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: refund-service
  template:
    metadata:
      labels:
        app: refund-service
    spec:
      containers:
      - name: refund-service
        image: firasmahjoubi/refund-service:latest
        ports:
        - containerPort: 8095
        envFrom:
        - configMapRef:
            name: refund-service-config
        - secretRef:
            name: refund-service-secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8095
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: refund-service
  namespace: ecommerce
spec:
  selector:
    app: refund-service
  ports:
  - port: 8095
    targetPort: 8095
  type: ClusterIP
